# Analysis parameters
threads: 8
window_size: 5000000
max_filter_length: 1000  # Maximum fragment length to keep in bam and bed files

# Fragment length definitions used for short and long fragments (low to cutpoint and cutpoint to high)
frag_length:
  low: 30
  high: 130
  cutpoints: [90, 100]  # List of cutpoints to use for short/long fragment analysis

# End motif parameters
motif_length: 4  # Length of end motifs to analyze

# Name pattern in bam files
bam_name_pattern: "{library}_aligned_dedup.bam"

# Directory structure
directories:
  analysis: "/mnt/data/urine/analysis"
  input_bams: "/mnt/data/urine/bams/dedup"
  filtered_bams: "/mnt/data/urine/bams/filt"
  beds: "/mnt/data/urine/beds"
  length_distros: "/mnt/data/urine/length_distros"
  medians: "/mnt/data/urine/medians"
  counts: "/mnt/data/urine/counts"
  gc_distros: "/mnt/data/urine/gc_distros"
  end_motifs: "/mnt/data/urine/end_motifs"
  bench: "/mnt/data/urine/benchmark"
  logs: "/mnt/data/urine/logs"
  ref: "/mnt/data/scripts/frag/ref"
  scripts: "/mnt/data/scripts/frag/scripts"

# Reference files
references:
  # Libraries file is a tab-separated file that must include at least the following columns: library, file(bam file path), and cohort.
  # One of the cohorts must be 'healthy'
  libraries_file: "/mnt/data/scripts/frag/ref/libraries.txt"
  genome_fasta: "/mnt/data/scripts/frag/ref/GRCh38.p13.genome.fa"
  blacklist: "/mnt/data/scripts/frag/ref/hg38-blacklist.v2.bed.gz"
  cytobands: "/mnt/data/scripts/frag/ref/cytoBand.txt"