# Analysis parameters
threads: 5
window_size: 5000000
max_filter_length: 1000  # Maximum fragment length to keep in bam and bed files

# Fragment length definitions used for short and long fragments (low to cutpoint and cutpoint to high)
frag_length:
  low: 30
  high: 130
  cutpoints: [90, 100]  # List of cutpoints to use for short/long fragment analysis

# Directory structure
directories:
  analysis: "/aclm350-zpool1/jlinford/test/frag_test/analysis"
  bams: "/aclm350-zpool1/jlinford/test/frag_test/analysis/bams"
  beds: "/aclm350-zpool1/jlinford/test/frag_test/analysis/beds"
  length_distros: "/aclm350-zpool1/jlinford/test/frag_test/analysis/length_distros"
  medians: "/aclm350-zpool1/jlinford/test/frag_test/analysis/medians"
  counts: "/aclm350-zpool1/jlinford/test/frag_test/analysis/counts"
  gc_distros: "/aclm350-zpool1/jlinford/test/frag_test/analysis/gc_distros"
  bench: "/aclm350-zpool1/jlinford/test/frag_test/benchmark"
  logs: "/aclm350-zpool1/jlinford/test/frag_test/logs"
  ref: "/aclm350-zpool1/jlinford/test/frag_test/ref"

# Reference files
references:
  libraries_file: "/aclm350-zpool1/jlinford/test/frag_test/ref/libraries.tsv"
  genome_fasta: "/aclm350-zpool1/jlinford/test/frag_test/ref/GRCh38.p13.genome.fa"
  blacklist: "/aclm350-zpool1/jlinford/test/frag_test/ref/hg38-blacklist.v2.bed.gz"
  cytobands: "/aclm350-zpool1/jlinford/test/frag_test/ref/cytoBand.txt"
