# Analysis parameters
threads: 5
window_size: 5000000
max_filter_length: 1000  # Maximum fragment length to keep in bam and bed files

# Fragment length definitions
frag_length:
  low: 80
  high: 200
  cutpoint: 130

# Name pattern in bam files
bam_name_pattern: "Sample_{library}.bam"

# Directory structure
directories:
  analysis: "/aclm350-zpool1/jlinford/gbm/frag/analysis"
  input_bams: "/logo2/irfan/GBM_project/GBM_batch2/FASTQ/aligned_bams"
  filtered_bams: "/aclm350-zpool1/jlinford/gbm/frag/analysis/bams"
  beds: "/aclm350-zpool1/jlinford/gbm/frag/analysis/beds"
  length_distros: "/aclm350-zpool1/jlinford/gbm/frag/analysis/length_distros"
  medians: "/aclm350-zpool1/jlinford/gbm/frag/analysis/medians"
  counts: "/aclm350-zpool1/jlinford/gbm/frag/analysis/counts"
  gc_distros: "/aclm350-zpool1/jlinford/gbm/frag/analysis/gc_distros"
  bench: "/aclm350-zpool1/jlinford/gbm/frag/benchmark"
  logs: "/aclm350-zpool1/jlinford/gbm/frag/logs"
  ref: "/aclm350-zpool1/jlinford/gbm/frag/ref"
  scripts: "/aclm350-zpool1/jlinford/frag/scripts"

# Reference files
references:
  # Libraries file is a tab-separated file that must include at least the following columns: library, file(bam file path), and cohort.
  # One of the cohorts must be 'healthy'
  libraries_file: "/aclm350-zpool1/jlinford/gbm/frag/ref/gbm_libraries.tsv"
  genome_fasta: "/logo2/irfan/GBM_project/GBM_batch2/reference/GRCh38-DAC-U2AF1.fna"
  blacklist: "/aclm350-zpool1/jlinford/frag/ref/hg38-blacklist.v2.bed.gz"
  cytobands: "/aclm350-zpool1/jlinford/frag/ref/cytoBand.txt"