name: frag
channels:
  - bioconda
  - conda-forge
  - no_defaults
dependencies:
  # --- Core runtime & workflow ---
  - python=3.11
  - snakemake-minimal=9.8

  # --- Python packages used by scripts ---
  - pandas=2.3
  - tqdm=4.67

  # --- Bioinformatics CLI tools ---
  - samtools=1.22
  - bedtools=2.31

  # --- R base and packages used by scripts ---
  - r-base=4.4
  - r-tidyverse=2.0
  - r-data.table=1.17
  - bioconductor-genomicranges=1.58